on:
  npm:
    name: actionsflow
jobs:
  slack:
    name: Send a message to Slack
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_RELEASE_WEBHOOK }}
        uses: Ilshidur/action-slack@2.1.0
        with:
          args: |
            New version (${{ on.npm.outputs.version }}) with actionsflow npm package
            
            <https://www.npmjs.com/package/actionsflow|Click here> for details